### ISSUE TITLE
SQS?

### ISSUE THREAD

**Issue by acruise** [aws/aws-kinesisanalytics-flink-connectors#21]
Hey folks, I'm baffled by the nonexistence of a popular SQS sink for Flink.... It's such a strange situation that I feel like I must be missing something obvious. Is it considered trivial to implement, or impossible to achieve commonality across diverse use cases, or what? :)

**Comment by dannycranmer** [comment]
Hello @acruise. You are not missing anything, there are currently no Amazon or Apache maintained SQS connectors for Flink. Are you interested in Source, Sink or both? We have recently implemented a new base sink framework that makes it easier to develop new Sinks for Flink 1.15 (https://cwiki.apache.org/confluence/display/FLINK/FLIP-171%3A+Async+Sink). 

I would advise to raise a Jira ticket directly in the Apache Flink jira https://issues.apache.org/jira/projects/FLINK/issues
